version: "3.9"
services:
  web:
    build: 
      context: web
    ports:
      - "5000:5000"
  api:
    build:
      context: api
    ports:
      - "8000:8000"
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: example

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

